name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and configure Docker Buildx builder
        run: |
          docker buildx create --use --name multiarch-builder --driver docker-container
          docker buildx inspect --bootstrap

      - name: Build and push multi-architecture image
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t iitgdocker/iperf-web:latest --push .

        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT: 1
